export const mockBlogs = [
  {
    id: 1,
    title: 'The Future of AI',
    description: 'Modernizing Admin Panels to developing huratic marking and suatothes, language and old business, content generation frameworks.',
    banner: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    author: 'Alice Green',
    authorInitials: 'A',
    authorBg: '#6d4c41',
    date: '2d ago',
    likes: 128,
    shares: 56,
    comments: 32,
    authorId: 626454
  },
  {
    id: 2,
    title: 'UI/UX Design Trends',
    description: 'UI/UX Best Practices to share what design to do strategy as ancounting your monitoring, internti and collaborative user flows.',
    banner: 'https://images.unsplash.com/photo-1545235617-9465d2a55698?auto=format&fit=crop&w=600&q=80',
    author: 'Jim Chen',
    authorInitials: 'J',
    authorBg: '#2e7d32',
    date: '2d ago',
    likes: 128,
    shares: 56,
    comments: 32,
    authorId: 626454
  },
  {
    id: 3,
    title: 'Scaling SaaS',
    description: 'Content Strategy is a consideration of rerisement, and comprating our entergengments, of content creation pipeline lifecycle.',
    banner: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
    author: 'Alice Green',
    authorInitials: 'S',
    authorBg: '#37474f',
    date: '2d ago',
    likes: 128,
    shares: 56,
    comments: 32,
    authorId: 626454
  },
  {
    id: 2,
    title: 'UI/UX Design Trends',
    description: 'UI/UX Best Practices to share what design to do strategy as ancounting your monitoring, internti and collaborative user flows.',
    banner: 'https://images.unsplash.com/photo-1545235617-9465d2a55698?auto=format&fit=crop&w=600&q=80',
    author: 'Jim Chen',
    authorInitials: 'J',
    authorBg: '#2e7d32',
    date: '2d ago',
    likes: 128,
    shares: 56,
    comments: 32,
    authorId: 626454
  },
  {
    id: 3,
    title: 'Scaling SaaS',
    description: 'Content Strategy is a consideration of rerisement, and comprating our entergengments, of content creation pipeline lifecycle.',
    banner: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
    author: 'Alice Green',
    authorInitials: 'S',
    authorBg: '#37474f',
    date: '2d ago',
    likes: 128,
    shares: 56,
    comments: 32,
    authorId: 626454
  },
  {
    id: 2,
    title: 'UI/UX Design Trends',
    description: 'UI/UX Best Practices to share what design to do strategy as ancounting your monitoring, internti and collaborative user flows.',
    banner: 'https://images.unsplash.com/photo-1545235617-9465d2a55698?auto=format&fit=crop&w=600&q=80',
    author: 'Jim Chen',
    authorInitials: 'J',
    authorBg: '#2e7d32',
    date: '2d ago',
    likes: 128,
    shares: 56,
    comments: 32,
    authorId: 626454
  },
  {
    id: 3,
    title: 'Scaling SaaS',
    description: 'Content Strategy is a consideration of rerisement, and comprating our entergengments, of content creation pipeline lifecycle.',
    banner: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
    author: 'Alice Green',
    authorInitials: 'S',
    authorBg: '#37474f',
    date: '2d ago',
    likes: 128,
    shares: 56,
    comments: 32,
    authorId: 626454
  },
  {
    id: 2,
    title: 'UI/UX Design Trends',
    description: 'UI/UX Best Practices to share what design to do strategy as ancounting your monitoring, internti and collaborative user flows.',
    banner: 'https://images.unsplash.com/photo-1545235617-9465d2a55698?auto=format&fit=crop&w=600&q=80',
    author: 'Jim Chen',
    authorInitials: 'J',
    authorBg: '#2e7d32',
    date: '2d ago',
    likes: 128,
    shares: 56,
    comments: 32,
    authorId: 626454
  },
  {
    id: 3,
    title: 'Scaling SaaS',
    description: 'Content Strategy is a consideration of rerisement, and comprating our entergengments, of content creation pipeline lifecycle.',
    banner: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
    author: 'Alice Green',
    authorInitials: 'S',
    authorBg: '#37474f',
    date: '2d ago',
    likes: 128,
    shares: 56,
    comments: 32,
    authorId: 626454
  },
  {
    id: 2,
    title: 'UI/UX Design Trends',
    description: 'UI/UX Best Practices to share what design to do strategy as ancounting your monitoring, internti and collaborative user flows.',
    banner: 'https://images.unsplash.com/photo-1545235617-9465d2a55698?auto=format&fit=crop&w=600&q=80',
    author: 'Jim Chen',
    authorInitials: 'J',
    authorBg: '#2e7d32',
    date: '2d ago',
    likes: 128,
    shares: 56,
    comments: 32,
    authorId: 626454
  },
  {
    id: 3,
    title: 'Scaling SaaS',
    description: 'Content Strategy is a consideration of rerisement, and comprating our entergengments, of content creation pipeline lifecycle.',
    banner: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
    author: 'Alice Green',
    authorInitials: 'S',
    authorBg: '#37474f',
    date: '2d ago',
    likes: 128,
    shares: 56,
    comments: 32,
    authorId: 626454
  },
  {
    id: 2,
    title: 'UI/UX Design Trends',
    description: 'UI/UX Best Practices to share what design to do strategy as ancounting your monitoring, internti and collaborative user flows.',
    banner: 'https://images.unsplash.com/photo-1545235617-9465d2a55698?auto=format&fit=crop&w=600&q=80',
    author: 'Jim Chen',
    authorInitials: 'J',
    authorBg: '#2e7d32',
    date: '2d ago',
    likes: 128,
    shares: 56,
    comments: 32,
    authorId: 626454
  },
  {
    id: 3,
    title: 'Scaling SaaS',
    description: 'Content Strategy is a consideration of rerisement, and comprating our entergengments, of content creation pipeline lifecycle.',
    banner: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
    author: 'Alice Green',
    authorInitials: 'S',
    authorBg: '#37474f',
    date: '2d ago',
    likes: 128,
    shares: 56,
    comments: 32,
    authorId: 626454
  },
  {
    id: 4,
    title: 'Remote Work Culture',
    description: 'Frontend Tech Stack is a pontessive and provider audiericen thar content and illimiva-ting successsful international setups.',
    banner: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&q=80',
    author: 'Mice Green',
    authorInitials: 'M',
    authorBg: '#5d4037',
    date: '2d ago',
    likes: 128,
    shares: 56,
    comments: 32,
    authorId: 626454
  }
];



export const popupIds ={
    "commentSidebar": "s4fsd12"
}